### ISSUE TITLE
enormous git history (165MB)

### ISSUE THREAD

**Issue by ahbarnett** [AndrewGibbs/PathFinder#1]
Dear Andrew,
Your git repo is 165MB but the current project size is 2.5BM.
Could you kill off the git history of whatever large files are causing this (PDF, .mexa64 ?) so it is more pleasant to download,
thanks? I'm not a git expert, but some rebase is needed.
Eg see
https://acquia.my.site.com/s/article/360004334093-Removing-large-files-from-Git-without-losing-history

Best, Alex

**Comment by AndrewGibbs** [comment]
Hi Alex,

Thanks for flagging this. Clearly I am also no git expert! Fortunately, your link was helpful - I've removed the larger bits of history now. The download is now 3.5Mb (1.5Mb compressed).

Best wishes,

Andrew
