### ISSUE TITLE
Optional inputs

### ISSUE THREAD

**Issue by DaveHewett** [AndrewGibbs/PathFinder#5]
Suggest throwing an error if an invalid (e.g. misspelled) optional input is added.

**Comment by AndrewGibbs** [comment]
Thanks for the suggestion Dave. This has been added to the latest version. For example, if you enter
```matlab
PathFinder(-1, 1, [], [1 0 0], 50, 10, 'fail');
```
You will see the error message `Optional input 'fail' not found`.
