### ISSUE TITLE
Compatibility with Octave

### ISSUE THREAD

**Issue by JamesGMcNally** [AndrewGibbs/PathFinder#6]
I have downloaded the PathFinder code, and have tried to run it using Octave. The test program:
PathFinder(-1,1,@(x) sin(x),[2 0 0],100,10,'plot')
does not run, and produces an error message:
get_smallest_supset_ball_mex
So as explained in the download instructions, I then tried to run compile_all.m in Octave, but this also did not run. 

I did some further investigation and see that unlike most Matlab and Octave commands, the command name for the Matlab coder (codegen) does not match the command name for the Octave coder (octave2oct), and the arguments in these function calls also do not match.  Furthermore, the coder.typeof statements that are indirectly called by compile_all.m do not seem to be available in Octave. So it seems at the moment, some work will be required to get the Matlab version of Pathfinder to run under Octave.

**Comment by AndrewGibbs** [comment]
Thanks for raising this Jim. This has now been fixed in the current version.
- PathFinder can be run in Octave
- Just incase the compilation fails for any reason, until it is fixed (by me) there is the option to run without MEX functions.
